version: "3"

services:
  caddy:
    image: snadn/caddy
    network_mode: "host"
    restart: always
    volumes:
      - ./config:/etc/caddy
      - ./data:/data
      - ./www:/www
    environment:
      - MAIL=snadn@snadn.cn
